# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sumkxPDRhSfkKod35aLYOkGqh160ZC5_
"""

import streamlit as st
from PyPDF2 import PdfReader
from docx import Document
import openai

# Function to read a PDF file
def read_pdf(file):
    reader = PdfReader(file)
    text = ""
    for page in reader.pages:
        text += page.extract_text()
    return text

# Function to read a Word (.docx) file
def read_word(file):
    doc = Document(file)
    text = "\n".join([para.text for para in doc.paragraphs])
    return text

# Function to generate text based on input sentences
def generate_text_based_on_sentences(sentence, api_key):
    openai.api_key = api_key
    messages = [
        {"role": "system", "content": "You are a helpful assistant that expands on given sentences."},
        {"role": "user", "content": f"Expand the following sentences into a paragraph:\n\n{sentence}"}
    ]
    response = openai.ChatCompletion.create(
        model="gpt-4",
        messages=messages,
        max_tokens=500,
        temperature=0.7
    )
    return response.choices[0].message['content']

# Streamlit app layout
st.title("Document Processor with OpenAI")

# OpenAI API Key input
api_key = st.text_input("Enter your OpenAI API Key:", type="password")

# File upload
uploaded_file = st.file_uploader("Upload a PDF or DOCX file", type=["pdf", "docx"])

if uploaded_file and api_key:
    # Check file type
    if uploaded_file.type == "application/pdf":
        document_text = read_pdf(uploaded_file)
    elif uploaded_file.type == "application/vnd.openxmlformats-officedocument.wordprocessingml.document":
        document_text = read_word(uploaded_file)

    st.write("Extracted Text:")
    st.write(document_text)

    # Generate Text from Sentences
    input_sentences = st.text_area("Enter 1 or 2 sentences to generate text from:")
    if input_sentences:
        generated_text = generate_text_based_on_sentences(input_sentences, api_key)
        st.write("Generated Text:")
        st.write(generated_text)