# -*- coding: utf-8 -*-
"""Image_Generation_Diffusion model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LeAnp0QU1Zr4BeVP0rYmY7NImXp612tl
"""

import torch
from diffusers import StableDiffusionPipeline
import streamlit as st
from PIL import Image

# Load the Stable Diffusion model from Hugging Face
pipe = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4")
pipe = pipe.to("cuda") if torch.cuda.is_available() else pipe.to("cpu")

# Streamlit app
def generate_image_from_text(prompt):
    with st.spinner('Generating image...'):
        image = pipe(prompt).images[0]  # Generate image
        return image

def main():
    st.title("Text to Image Generator")

    # Input for text prompt
    prompt = st.text_input("Enter a text prompt:")

    if st.button("Generate"):
        if prompt:
            # Generate the image from the prompt
            image = generate_image_from_text(prompt)
            st.image(image, caption="Generated Image", use_column_width=True)

            # Save the image
            image.save("generated_image.png")
            st.success("Image saved as 'generated_image.png'")
        else:
            st.warning("Please enter a prompt to generate an image.")

if __name__ == "__main__":
    main()